### PR TITLE
Update listing

### PR DESCRIPTION
**Pull request by ThebergeV**
Update Listing Feature.

The "Update Listing" button appears in the listing cards if you are a landlord. Clicking it opens a page with autofilled boxes. Changing these boxes and clicking update updates the listing

### CODE REVIEW

**Comment by YongDeYu** [comment]
everything works, except one thing. The apartment number. It keeps resetting every time you go to update it. Is it possible to keep the same one? I tried setting a listing as apt 1, then when I went into the update listing page, it reset to undefined

**Comment by MarcVida** [comment]
It seems your code for `UpdateListing.js` is based on the `main` version of the `CreateListing.js` component, which has some issues (including the apartment number bug). All of those issues were fixed in the `create-fixing-newer` branch. Check #35 for more details

**Comment by ThebergeV** [comment]
@MarcVida ahh damn, would've made my life easier. I will check that branch but otherwise does it look good to you ?

**Comment by MarcVida** [comment]
Ok so I tested it and the other issues are still there as expected, unfortunately. To name a few:
* when all utilities are empty, the server responds with 500
* property type cannot be changed

**Comment by ThebergeV** [comment]
@MarcVida so should I change that or would that be changed automatically once the other pr is merged ?

**Pull request merged**
