### PR TITLE
BE - Save the listing details in the database

### PR DESCRIPTION
**Pull request by Chrishatoum**

### CODE REVIEW

**Comment by abdul-ali98** [comment]
1- Endpoint should accept images, I do not see it in the arguments, Could you confirm pls? 
2- The listing does not seem to be added to the landlord? in Landlord.java, we keep track of every listing they post.
2- @SamySabir Can you please submit test cases?  so we make sure that it works as expected

**Comment by SamySabir** [comment]
Test cases for which feature exactly? Which backlog entry

**Comment by Chrishatoum** [comment]
> 1- Endpoint should accept images, I do not see it in the arguments, Could you confirm pls?  

check the new update adding the image and utilites.

**Review by abdul-ali98 — CHANGES_REQUESTED** [review]
1- In the controller, you always pass images as null, How do you save them? 
2- After you save a listing to the database, How do you know which landord has posted that listing? Can you please add it to the Landlord listings in the database to ensure integrity? 
expected: when we lookup landlord's listings, we should find this listing. you can add the if of this listing to the landlord.
3- Did you test the code and inserted a new listing in the database? If yes, Can you provide me with steps of cmds you used so I test it on my end?

**Comment by MarcVida** [comment]
@abdul-ali98 Should we close this pr? #13 was already approved so I don't think we need this one anymore

**Comment by vladimirven001** [comment]
i believe we can close this one

**Comment by abdul-ali98** [comment]
Based on the discussion on today's meeting. This is a duplicate and could be closed

**Pull request closed without merging**
