### PR TITLE
Landlord approval FE + Sign In

### PR DESCRIPTION
**Pull request by ThebergeV**
Front end for the landlord approval and Sign In

The backend commands need to be implemented in front end

### CODE REVIEW

**Comment by kookiekookie** [comment]
When Approving Landlords:
-Design intent is to see list of pending landlords, then approve them by activating their account and be sent to a form page with all their information except Reason filled out. Then the approval can be confirmed after giving a reason. "Decline" is also an option though it wouldn't do anything new to the account (my assumption)
-Username text box can not be typed into
-Phone Number text box takes 1 character at a time before forcing exit out, and resets all other text boxes
-Phone Number text box always returns "Phone number is required for landlords." regardless of input
-Reason and email text box is fine

All error messages for missing text boxes are good, although clicking Approve or Decline currently resets every text box except Phone Number.

**Comment by vladimirven001** [comment]
@ThebergeV could you check out the frontend sign in code for handleSubmit in add-authentication branch, and maybe add it to this, so that we can merge this PR with the signin component complete

**Comment by vladimirven001** [comment]
Actually @ThebergeV, could you remove the signin component from this PR, I am having some issues with the sign in backend, so ill merge everything once my backend is working, it will be hard to do it the frontend component is already merged
plus it keeps this PR more specific to landlord approval

Once again, sorry about not mentionning the work on the login component before!

**Comment by ThebergeV** [comment]
Fixed the issues, this can be tested and merged. The conflict in app is simple to solve: just need to include both the code from main and this pr. I couldn't do it because fixing the issues would have also merged this pr with main, skipped the review.

**Comment by ThebergeV** [comment]
@vladimirven001 can we merge this ? The merge conflict is very simple to change (see my previous comment). If I fix the conflict in github it seems to want to merge immediatly after which is why I didn't do it. But if everything is fine I'll do it

**Comment by vladimirven001** [comment]
yes ill go check it out now

**Comment by vladimirven001** [comment]
we can merge, i added security for when a non landlord is logged which hides the page and button

**Pull request merged**
