### PR TITLE
Task 8 - Week 1 Sprint B Task List - Create View Listings Page w/ Mock Listings

### PR DESCRIPTION
**Pull request by jkzcodes**
Task 8 - Week 1 Sprint B Task List

### CODE REVIEW

**Review by vladimirven001 — COMMENTED** [review]
i added the navbar in 8f976d2, also please be more specific with the pr, i.e. what it does, and what it doesn't, in any case, i think we need to create or wait for the creation of the backend for getting all listings

**Comment by MarcVida** [comment]
The backend for getting all listings has already been implemented in #13. It was done as part of the task "Update a Listing" since we needed to verify that the listings can be updated

**Comment by jkzcodes** [comment]
@MarcVida theres is no interaction between the front-end and the backend though right? the only way to currently have listings in the database is to manually impute them, correct?

**Comment by MarcVida** [comment]
@jkzcodes I don't know about the frontend, but currently you can use the REST API to create, update and get listings. I wrote an example in this comment: https://github.com/DenzelleJinx/ECSE-428-Fall-2024/pull/13#issuecomment-2458102647

**Comment by jkzcodes** [comment]
@MarcVida Omg awesome! I had not seen this. Will not have time to implement the fetching for this week, but I will get it done next week. Ideally by then, clicking on 'Create Listing' will trigger an addition to the db.

**Pull request merged**
